#!/bin/bash
branch="main" 
git_url="https://github.com/user/repo.git"
jenkins_url="http://jenkins-server/job/my-job/build"
jenkins_user="user"
jenkins_token="token"

# Clone repository and pull latest changes
git clone $git_url repo
cd repo
git checkout $branch 
git pull

# Trigger Jenkins pipeline
curl -X POST $jenkins_url \
  --user "$jenkins_user:$jenkins_token" 
echo "CI/CD pipeline triggered for branch $branch." 
